### ISSUE TITLE
test 1, 2, 3 and 4 fail in test-calc-4pmk on cygwin 64 using clang

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1835]
While testing #1834 ```fix-for-1834``` branch, the following came up (which is similar to #1833) after using ```./configure CC=clang CXX=clang++``` followed by ```make check```:

```
=============================================================
   aircrack-ng 1.2-rc4: test/cryptounittest/test-suite.log
=============================================================

# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-calc-4pmk
====================

[./test-calc-4pmk][Test 1] ERROR: The output don't match. I got:
f2 37 0a fd ca 54 d5 e2 92 15 c8 ab d8 ce 3d 7f
1e 10 8b 07 b1 6b 65 c2 5d 0a 30 c3 cc 26 72 9f

And I was expecting:
cd d7 9a 5a cf b0 70 c7 e9 d1 02 3b 87 02 85 d6
39 e4 30 b3 2f 31 aa 37 ac 82 5a 55 b5 55 24 ee

[./test-calc-4pmk][Test 2] ERROR: The output don't match. I got:
42 ce 6d 9c 5c 9b cb 7f b0 38 3a 14 19 b8 f2 70
8e 8d 9a ff 81 fe e8 36 f3 2d 95 48 dd aa 01 c8

And I was expecting:
9a 15 ed 29 a9 b8 0e 5d 52 32 a0 64 4c fd 40 4b
83 97 9b 57 af 83 05 80 6d d4 d4 86 50 06 ed 7d

[./test-calc-4pmk][Test 3] ERROR: The output don't match. I got:
a9 fa 50 94 04 61 56 2f ef 94 59 9c b4 0c c7 93
b6 47 e8 b3 e3 74 0d 71 36 fa 4c 3d fc 9a 51 3c

And I was expecting:
12 8c 41 ed f5 32 1c 51 1f d6 af 07 96 95 df 71
5c b1 b7 68 6f 1a ed e9 70 1e 87 07 b8 c9 b4 3b

[./test-calc-4pmk][Test 4] ERROR: The output don't match. I got:
89 51 c0 fe c5 26 a2 c5 a2 ba 29 f0 07 d1 b2 f9
9e a1 18 a9 12 7f 94 40 70 f9 8a f7 11 61 e2 34

And I was expecting:
bb 84 66 33 ef 41 5a b6 cd 83 93 c6 00 18 26 42
76 62 7c 4e bc 6b 8f 20 9b be 59 b4 86 71 69 dd

[./test-calc-4pmk][Test 5] OK: Output matches :)
[./test-calc-4pmk][Test 6] OK: Output matches :)
[./test-calc-4pmk][Test 7] OK: Output matches :)
[./test-calc-4pmk][Test 8] OK: Output matches :)
FAIL test-calc-4pmk.exe (exit status: 4)
```

**Comment by jbenden** [comment]
After thoroughly researching this matter, I settled on a less-than-ideal, yet working, solution. I currently have the combination of Cygwin and Clang dispatching through `calc_pmk` (four times, in a loop) like non-Intel processors would do (see `sha1-sse2.h` near the end-of-file.)

In my research, I determined that Clang uses the same calling convention as GCC, and more precisely; the standard Windows x64 calling convention. This uses the registers `rcx`, `rdx`, and `r8`, in this order, for the first three parameters passed.

When Clang is told to *NOT* use optimizations (`-O0`), the code works perfectly and all unit-tests pass.

However, as soon as **ANY** optimizations (even code size related ones) are enabled; a disassembly shows that the parameters to our assembly functions are *never* actually loaded into the registers; and therefore, everything fails.

It seems as if this is a bug in Clang and the patches applied to it, by the Cygwin project.

If anyone is up to discussing this matter with Cygwin's team or with Clang's team, please drag me in to the conversation. Otherwise, I am considering this bug fixed, as of commit 3d3237ef961f1cadc1cb5fadc5c6b133fcbbd4eb.
