### ISSUE TITLE
BOLD objection to creeping introduction of GLIB

### ISSUE THREAD

**Issue by rofl0r** [aircrack-ng/aircrack-ng#1909]
6 days ago, starting with commit 8f5fe6feb014694781dde0271626538c4e835a2b a dependency on GLIB has been creepily introduced into the build process by @jbenden even though i can not see it used anywhere in the code.

this looks to me as if @jbenden intends to start using it in the future and paves the way.

i'm highly opposed to this move for several reasons:
- introducing new dependencies is generally a bad thing
- glib in particular is a very [badly designed](http://suckless.org/sucks) and huge library. the entire install weighs in at 34.5 MB and it consists of 1059 files (when configured without "GIO" and "GIR" options)
- many people use aircrack-ng on routers, they just cant afford the additional 35 MB used by the glib library framework.
- glib is a redhat/gnome way of life even moreso than a library and is basically meant as a C++ standard library for C.
- this move looks like an ideological zealotry move to me, getting more and more GNU/Gnome crap into aircrack-ng, similar to when C++ zealots lobby C projects like GCC until they subverted them successfully.
- it sucks

i'm considering forking aircrack-ng to keep this crap out. that then would become aircrack-ng-ng.

@Mister-X- ^ @aircrack-ng

**Comment by DJDan** [comment]
I failed to cross-compile latest git for my LEDE router due to the new GLIB dependency and i don't even have 35 MB space on it to install GLIB on it.

I cross compile from a macOS High Sierra 10.13.5 machine to a MIPSEL based XIAOMI WIFI 3G Router that uses LEDE. This router has limited space available generally, let alone when I add other programming things to it for my own use or precompiled larger binary files. The LEDE programming team themselves has even removed/modified a lot of the usual useful Linux libraries to reduce the system drive's overhead.

Please make aircrack-ng easy to cross compile without adding extra file space overhead so that I can continue to use a great utility on all my devices. It was way easier to cross compile without the added library constraint.

Thanks
@rofl0r @jbenden @aircrack-ng

**Comment by jbenden** [comment]
Removed!

**Comment by rofl0r** [comment]
thanks! for the record, this was the commit https://github.com/aircrack-ng/aircrack-ng/commit/3b724e8b91f20f83d92229c4b67d646841d33b93
