### ISSUE TITLE
Realtek chipset 

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#1935]
```
sudo airmon-ng
PHY	Interface	Driver		Chipset

null	enx000f0066ec11	??????		Realtek Semiconductor Corp. 
phy0	wlp3s0		iwlwifi		Intel Corporation Wireless 3160 (rev 83)``
```
Realtek chipset is not allowing me to change to monitor mode. I try to do it manually and it wont work either.

Any suggestions?

**Comment by aircrack-ng** [comment]
This is most likely a vendor driver considering that there is no phy linked to it or driver that can be found. Not a single vendor driver support monitor mode.

Check our documentation to find out the chipset and figure out if there is an open source driver for it: https://aircrack-ng.org/doku.php?id=compatibility_drivers

Feel free to reopen this issue if this is a bug in airmon-ng. Otherwise, this is a support request and those are handled in the forum.
