### ISSUE TITLE
bug with the aircrack-ng  gui wordlist option 

### ISSUE THREAD

**Issue by minanagehsalalma** [aircrack-ng/aircrack-ng#2028]
i can't choose more than one wordlist

![image](https://user-images.githubusercontent.com/20546638/53587131-43c8ae00-3b92-11e9-804e-98f0ad5a6317.png)

the two word lists paths 
"E:\optimized ist.txt" "E:\programs\passwords .txt"

**Comment by aircrack-ng** [comment]
You are probably using an old version. It is fixed in the current version.

Please follow the bug reporting guidelines. Version information is very important, and in this case, the GUI generates a log file which helps debugging issues.

Feel free to reopen the bug if present in current stable and in this case, append the log file from the GUI.

**Comment by minanagehsalalma** [comment]
@aircrack-ng  no it's not  i am using the latest version already (aircrack-ng-1.5.2-win)
the log file 
[debug.log](https://github.com/aircrack-ng/aircrack-ng/files/2920422/debug.log)

**Comment by minanagehsalalma** [comment]
Where can I download the fixed version ?!

**Comment by aircrack-ng** [comment]
Clone the repository, switch to 'Windows' branch then compile the solution in the GUI folder using Visual Studio.

**Comment by minanagehsalalma** [comment]
But I don't use visual studio ..
Or even know how to use it

**Comment by aircrack-ng** [comment]
[Aircrack-ng GUI.zip](https://github.com/aircrack-ng/aircrack-ng/files/2922604/Aircrack-ng.GUI.zip)

**Comment by minanagehsalalma** [comment]
@aircrack-ng  thanks
