### ISSUE TITLE
Besside-ng doesn't validate client

### ISSUE THREAD

**Issue by RChadwick7** [aircrack-ng/aircrack-ng#2077]
I'm running this on Nethunter on a Nexus 5. I tried cracking an AP that had no clients (Wifite said there were no clients, Besside-ng said there was one). When I try to connect to the AP, WITH THE WRONG PASSWORD, Besside-ng captures the handshake happily and saves it as a good handshake. The handshake might be good, and can even be cracked, but will reveal the wrong password.

# Issue type
- Defect - Incorrect value displayed/received/stored
- Defect - Unexpected behavior (obvious or confirmed in the forum)

**Comment by aircrack-ng** [comment]
That is because aircrack-ng can deal with incomplete handshake, such as when wireless signal is weak, where one or 2 missed packets can still be cracked. Thus, when a client (fake or real) uses an invalid password, the invalid password will be cracked. 

You can filter the handshake to give to aircrack-ng, and favor more complete handshakes if possible. There is a tutorial to help with selecting packets: https://aircrack-ng.org/doku.php?id=wpa_capture
