### ISSUE TITLE
Errors putting RTL8812AU into monitor mode (AWUS036ACH)

### ISSUE THREAD

**Issue by Kriskras99** [aircrack-ng/aircrack-ng#2147]
# Issue type
- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information
- OS: Arch Linux (Kernels 5.6.14-arch1-1 & 5.4.42-1-lts), also happens on Kali 2020.1
- CPU: Intel i7-7700HQ
- Wireless card and chipset: Alfa AWUS 036ACH / RTL8812AU
- Driver versions: [5.6.4.2 / 5.6.4 / 5.7.0 / 5.3.4](https://github.com/aircrack-ng/rtl8812au)

# Aircrack-ng version
- Version: 1.6
- Commit Revision hash: Could not build master, something to do with: `multiple definition of '__packed'`

# Defect
## How to reproduce the issue

1. Install rtl88xxau-aircrack-dkms-git
2. Disable NetworkManager and wpa_supplicant
3. `airmon-ng check` shows nothing
4. `airmon-ng start wlan1`
5. `Newly created monitor mode interface wlan1mon is *NOT* in monitor mode.`
6. Sometimes it also reports a segfault

The card does go into monitor mode using `iw dev`
## Related issues 
See the [rtl8812au](https://github.com/aircrack-ng/rtl8812au/issues/646) issue for a call trace

**Comment by username7291** [comment]
airmon-ng supports only some drivers
even manual
    sudo ip link set wlan0 down
    sudo iw dev wlan0 set type monitor
    sudo ip link set wlan0 up
can fail. Or freeze/crash the whole system.
sometimes you need to use iw/ip sometimes iwconfig/ifconfig. If you do wrong steps
the driver dont work with the right steps after it. You need todo "modprobe -r xxxx" & "modeprobe xxxx" to make it work again.
Some drivers not even support monitor mode. Thats linux driver quality.
But after the manual mode you can use airodump-ng without airmon-ng.
With other words since newer airodump-ng versions airmon-ng is not required anymore, common drivers are supported by airodump-ng without doing anything before.

**Comment by ZeroChaos-** [comment]
This is fixed in master now. No release yet contains the fix but you can pull a patch of you need it
