### ISSUE TITLE
Check compilation and tests with OpenSSL 3.0

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2222]
# Description

OpenSSL 3.0 is the next release of OpenSSL that is currently in development.

We need to test it to ensure it still compiles and work with it or if things need to be adjusted.

URL: https://wiki.openssl.org/index.php/OpenSSL_3.0

**Comment by ZerBea** [comment]
Running OpenSSL 3.0 many functions became deprecated:
That include all HMAC(EVP_....) functions as well as all CMAC_(...) functions, all SHA1_(...) functions and more non EVP functions. To avoid a warning, they should be replaced by EVP API, eg.:
```
mdctx = EVP_MD_CTX_new();
pkey = EVP_PKEY_new_mac_key(EVP_PKEY_HMAC, NULL, pmk, 32);
EVP_DigestSignInit(mdctx, NULL,  EVP_sha1(), NULL, pkey)
btw on KDV1: EVP_DigestSignInit(mdctx, NULL,  EVP_md5(), NULL, pkey)
btw on KDV2 keyver 3: EVP_DigestSignInit(mdctx, NULL,  EVP_sha256(), NULL, pkey)
EVP_DigestSignUpdate(mdctx, message, messagelen)
EVP_DigestSignFinal(mdctx, testpmkid, &testpmkidlen) 
EVP_PKEY_free(pkey);
EVP_MD_CTX_free(mdctx);
```
Otherwise you'll receive this ugly warnings:
warning: 'SHA1_Init' is deprecated: Since OpenSSL 3.0
warning: 'HMAC' is deprecated: Since OpenSSL 3.0 
warning: 'CMAC_Init' is deprecated: Since OpenSSL 3.0
