### ISSUE TITLE
Compilation error on GCC 10 due to multiple definitions of __packed

### ISSUE THREAD

**Issue by abdelmoumen-eddaoudy** [aircrack-ng/aircrack-ng#2281]
## Details

- Starting from the upcoming GCC release 10, the default of `-fcommon option` will change to `-fno-common` - this leads to build errors:
```
Making all in scripts
make[2]: Entering directory '/root/aircrack-ng-1.6/scripts'
make[3]: Entering directory '/root/aircrack-ng-1.6/scripts'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/root/aircrack-ng-1.6/scripts'
make[2]: Leaving directory '/root/aircrack-ng-1.6/scripts'
make[2]: Entering directory '/root/aircrack-ng-1.6'
  CCLD     libaircrack-osdep.la
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libradiotap.a(radiotap.o):(.bss+0x0):
multiple definition of `__packed'; lib/osdep/.libs/libaircrack_osdep_la-linux.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2991: libaircrack-osdep.la] Error 1
make[2]: Leaving directory '/root/aircrack-ng-1.6'
make[1]: *** [Makefile:4805: all-recursive] Error 1
make[1]: Leaving directory '/root/aircrack-ng-1.6'
make: *** [Makefile:2580: all] Error 2
```

**Comment by abdelmoumen-eddaoudy** [comment]
This was a problem with `radiotap-library` as they use `__packed` instead of `__attribute__((__packed__))`.

**Comment by gemesa** [comment]
This issue is already fixed in [radiotap/radiotap-library](https://github.com/radiotap/radiotap-library), see [this PR](https://github.com/radiotap/radiotap-library/pull/6) and in [aircrack-ng/aircrack-ng](https://github.com/aircrack-ng/aircrack-ng) also, see [this commit](https://github.com/aircrack-ng/aircrack-ng/commit/d4496006ac1e0c99908108b998ae39afb0658733). Issue can be closed if you agree @Mister-X-
